### ISSUE TITLE
Mac interface

### ISSUE THREAD

**Issue by epipheus** [goldshellminer/HS1#1]
Is there only a Windows driver and interface? Why? *nix is much easier.

**Comment by goldshellminer** [comment]
Hi


&nbsp; &nbsp;&nbsp;The official software does not currently support it, the third-party software Handyminer is recommended






------------------

 Sincerly
Goldshell Official Customer Service Team

 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by epipheus** [comment]
Is there an api you document so that we can build our own?

**Comment by goldshellminer** [comment]
Sorry, we don't have an API right now. 
You can check the serial communication protocol docs to implement that : Goldshell-HS1_Serial communication protocol_V0.4.pdf
Or you can check with handyminer's implementation source code.
