### ISSUE TITLE
Support for Nicehash?

### ISSUE THREAD

**Issue by Machieps** [goldshellminer/HS1#2]
The software random generates a username so it cannot be used for nicehash or MMR, is there a way that the software could work for this?

**Comment by goldshellminer** [comment]
Hello Sir,  have you try nicehash with Handyminer? It may work with nicehash.

**Comment by Machieps** [comment]
I have tried Handyminer, but when Nicehash order ends and a new one starts, the miner gives an error and stops hashing. :(
