### ISSUE TITLE
submit of Stratum

### ISSUE THREAD

**Issue by ruyichang** [goldshellminer/HS1#3]
hello,
I recently tested the HS1 minner, and i found that mining.submit of HS1 is not the same with what the hstratum 
https://github.com/HandshakeAlliance/hstratum/blob/master/docs/spec.md
This is demo of hstratum
```
mining.submit
mining.submit("username", "job id", "ExtraNonce2", "nTime", "nOnce")

This call is used to submit a share of work to the pool. The parameters are as follows:

The worker name.
Job ID
ExtraNonce2.
Time used in block header.
nOnce.
```
And this is result of HS1 which i've tested
```
{"method":"mining.submit","id":7,"params":["user.H10B0291C354D4","2","00000002","5fbe2bcf","338fccec","0000000000000000000000000000000000000000000000000000000000000000"]}
```
Is there any documentation for these？
Thank you.

**Comment by goldshellminer** [comment]
hello sir, goldshell HS1 report the result as following:
{username,  jobid,  extranonce2, ntime, nonce, maskhash}
